# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

spring:
  # ThymeleafProperties
  thymeleaf:
    cache: false

  # MailProperties
  mail:
    host: smtp.163.com  # 发送邮件的服务器地址
    port: 465 # 端口号，一般是 465或 994
    username: junzemo@163.com # 网易邮箱
    password: QLFGACHISAJKKQTA  # 客户端授权码
    protocol: smtp  # 发送邮件协议
    properties.mail.smtp.ssl.enable: true #开启SSL

  # DataSourceProperties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: m04jz17
    # 连接池类型
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15 # 最大连接数
      minimum-idle: 5 # 最小空闲连接
      idle-timeout: 30000 # 超时时间

  # MyBatisProperties
mybatis:
  # 映射文件的存放位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类所在包
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    # 启用自增长主键
    useGeneratedKeys: true
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: true

# community:配置激活链接
community:
  path:
    domain: http://localhost:8080
    upload: d:/notebook/仿牛客网社区开发-所有素材和源码/upload
# logger 打印 sql,方便调试
#logging:
#  level:
#    com.nowcoder.community: debug
#  # 日志存放目录
#  file:
#    path: D:/note/nowcoder/community